### ISSUE TITLE
Trivial kernel does not work for `triton==3.2.0`

### ISSUE THREAD

**Issue by vvvm23** [jax-ml/jax-triton#330]
Running the follow vector add kernel:
```python
import triton
import triton.language as tl

import jax
import jax.numpy as jnp
import jax_triton as jt

@triton.jit
def add_kernel(
    x_ptr,
    y_ptr,
    length,
    output_ptr,
    block_size: tl.constexpr,
):
  """Adds two vectors."""
  pid = tl.program_id(axis=0)
  block_start = pid * block_size
  offsets = block_start + tl.arange(0, block_size)
  mask = offsets < length
  x = tl.load(x_ptr + offsets, mask=mask)
  y = tl.load(y_ptr + offsets, mask=mask)
  output = x + y
  tl.store(output_ptr + offsets, output, mask=mask)



def add(x: jnp.ndarray, y: jnp.ndarray) -> jnp.ndarray:
  out_shape = jax.ShapeDtypeStruct(shape=x.shape, dtype=x.dtype)
  block_size = 8
  return jt.triton_call(
      x,
      y,
      x.size,
      kernel=add_kernel,
      out_shape=out_shape,
      grid=(x.size // block_size,),
      block_size=block_size)

def main():
  x = jax.numpy.arange(16)
  y = jax.block_until_ready(add(x, x))
  print(y)


if __name__ == "__main__":
  main()
```

Does not work on `triton==3.2.0`.

Using `jax-triton` from pypi the error is:
```
Traceback (most recent call last):
  File "/root/repos/triton_repro/main.py", line 47, in <module>
    main()
  File "/root/repos/triton_repro/main.py", line 42, in main
    y = jax.block_until_ready(add(x, x))
  File "/root/repos/triton_repro/main.py", line 31, in add
    return jt.triton_call(
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax_triton/triton_lib.py", line 847, in triton_call
    out_flat = triton_kernel_call_p.bind(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: AttributeError: 'JITFunction' object has no attribute '_get_config'

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/repos/triton_repro/main.py", line 47, in <module>
    main()
  File "/root/repos/triton_repro/main.py", line 42, in main
    y = jax.block_until_ready(add(x, x))
  File "/root/repos/triton_repro/main.py", line 31, in add
    return jt.triton_call(
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax_triton/triton_lib.py", line 847, in triton_call
    out_flat = triton_kernel_call_p.bind(
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax/_src/core.py", line 502, in bind
    return self._true_bind(*args, **params)
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax/_src/core.py", line 520, in _true_bind
    return self.bind_with_trace(prev_trace, args, params)
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax/_src/core.py", line 525, in bind_with_trace
    return trace.process_primitive(self, args, params)
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax/_src/core.py", line 1024, in process_primitive
    return primitive.impl(*args, **params)
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax/_src/dispatch.py", line 90, in apply_primitive
    outs = fun(*args)
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax_triton/triton_lib.py", line 626, in triton_kernel_call_lowering
    kernel, specialization_attr = get_or_create_triton_kernel(
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax_triton/triton_lib.py", line 375, in get_or_create_triton_kernel
    specialization_attr = fn._get_config(*args_for_specialization_attr)  # pylint: disable=protected-access
AttributeError: 'JITFunction' object has no attribute '_get_config'
```

from `jax-triton` `main` the error is different:
```
Traceback (most recent call last):
  File "/root/repos/triton_repro/main.py", line 47, in <module>
    main()
  File "/root/repos/triton_repro/main.py", line 42, in main
    y = jax.block_until_ready(add(x, x))
  File "/root/repos/triton_repro/main.py", line 31, in add
    return jt.triton_call(
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax_triton/triton_lib.py", line 845, in triton_call
    out_flat = triton_kernel_call_p.bind(
jax._src.source_info_util.JaxStackTraceBeforeTransformation: AttributeError: module 'triton.runtime.jit' has no attribute 'specialize_impl'

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/repos/triton_repro/main.py", line 47, in <module>
    main()
  File "/root/repos/triton_repro/main.py", line 42, in main
    y = jax.block_until_ready(add(x, x))
  File "/root/repos/triton_repro/main.py", line 31, in add
    return jt.triton_call(
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax_triton/triton_lib.py", line 845, in triton_call
    out_flat = triton_kernel_call_p.bind(
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax/_src/core.py", line 502, in bind
    return self._true_bind(*args, **params)
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax/_src/core.py", line 520, in _true_bind
    return self.bind_with_trace(prev_trace, args, params)
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax/_src/core.py", line 525, in bind_with_trace
    return trace.process_primitive(self, args, params)
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax/_src/core.py", line 1024, in process_primitive
    return primitive.impl(*args, **params)
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax/_src/dispatch.py", line 90, in apply_primitive
    outs = fun(*args)
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax_triton/triton_lib.py", line 600, in triton_kernel_call_lowering
    kernel, specialization_attr = get_or_create_triton_kernel(
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax_triton/triton_lib.py", line 366, in get_or_create_triton_kernel
    specialization = [
  File "/root/repos/triton_repro/venv/lib/python3.10/site-packages/jax_triton/triton_lib.py", line 367, in <listcomp>
    triton.runtime.jit.specialize_impl(
AttributeError: module 'triton.runtime.jit' has no attribute 'specialize_impl'
```

Could the library be updated? This prevents using a lot of nice new features in triton only available in later versions, such as Blackwell specific stuff.

I have tested on `jax[cuda12]==0.5.[0,1]` with same result – I imagine this would also happen on `0.4.xx` but have not tested.

**Comment by reachtarunhere** [comment]
Facing the exact same issue.
