### ISSUE TITLE
jax-triton 0.3.0 release does not work with triton 3.5.x releases. And other version mismatches

### ISSUE THREAD

**Issue by tdophung** [jax-ml/jax-triton#365]
**1. When using jax-triton release version 0.3.0 + triton release version 3.5.x, some argument was not passed into triton's cuda_backend.make_ttir()**

```
/home/tdophung/.local/lib/python3.12/site-packages/jax_triton/triton_lib.py:615: in triton_kernel_call_lowering
    kernel, specialization_attr = get_or_create_triton_kernel(
/home/tdophung/.local/lib/python3.12/site-packages/jax_triton/triton_lib.py:450: in get_or_create_triton_kernel
    compilation_result = compile_ttir_inplace(
/home/tdophung/.local/lib/python3.12/site-packages/jax_triton/triton_lib.py:190: in compile_ttir_inplace
    return compile_ttir_to_ptx_inplace(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ttir = <triton._C.libtriton.ir.module object at 0xfffc3450ab70>, cuda_backend = <triton.backends.nvidia.compiler.CUDABackend object at 0xfffc3477cd70>
cuda_options = CUDAOptions(num_warps=32, num_ctas=1, num_stages=3, warp_size=32, maxnreg=None, cluster_dims=(1, 1, 1), ptx_version=No...b/libdevice.10.bc'),), debug=False, backend_name='cuda', sanitize_overflow=True, arch='sm100', instrumentation_mode='')
compute_capability = 100


    def compile_ttir_to_ptx_inplace(
        ttir,
        cuda_backend: cb.CUDABackend,
        cuda_options: cb.CUDAOptions,
        compute_capability,
    ) -> CompilationResult:
      if cuda_options.debug:
        print(ttir)
      try:
        metadata = {}
>       opt_ttir = cuda_backend.make_ttir(ttir, metadata, cuda_options)
E       TypeError: CUDABackend.make_ttir() missing 1 required positional argument: 'capability'
E       --------------------
E       For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

/home/tdophung/.local/lib/python3.12/site-packages/jax_triton/triton_lib.py:220: TypeError
```

I also tried this with older triton like 3.4 but it also running into the same issue

**2. When I try building jax-triton  from source from main, the latest commit at 6b9682ae35968507d60efc3c799dfb7bfc89dc46 (Oct 15) and using it with triton 3.5.x, 3.3.0, 3.4.0, all failed with** 
```
`E     AttributeError: module 'triton._C.libtriton' has no attribute 'native_specialize_impl'
E     --------------------
E     For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

/home/tdophung/.local/lib/python3.12/site-packages/jax_triton/triton_lib.py:369: AttributeError`
```

I notice that the ci for this commit is failing with the same signature also. After checking triton repo, I realized that this 'native_specialize_impl' is not available on any releases of triton as of now, only on the main branch, and was committed on Sep 8

**3. After going back 1 commit on jax-triton , it finally worked! I built at 0c6c888a7d350cb45aeb87210857b8cc76dd2e92. Works with 3.5.x triton release versions**

**Comment by superbobry** [comment]
Resolving now that 0.4.0 is on PyPI.
